// src/mockData/nftCollections.js
export const NFT_COLLECTIONS = [
  {
    id: 'collection-1',
    name: 'Somnia Punks',
    description: '10,000 unique digital collectibles living on the Somnia blockchain',
    creator: '0x742d35Cc6634C893292Ce8bB6239C002Ad8e6b59',
    contractAddress: '0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359',
    totalSupply: 10000,
    floorPrice: '0.5',
    volumeTraded: '12500',
    createdAt: '2024-01-15T00:00:00Z',
    bannerImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco',
    profileImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco',
    website: 'https://somniapunks.io',
    twitter: 'https://twitter.com/somniapunks',
    discord: 'https://discord.gg/somniapunks',
    verified: true,
    category: 'PFP',
    chain: 'Somnia',
    royalties: 7.5,
    traits: [
      { name: 'Background', values: ['Blue', 'Red', 'Green', 'Purple'] },
      { name: 'Type', values: ['Human', 'Alien', 'Zombie', 'Ape'] },
      { name: 'Mouth', values: ['Smile', 'Frown', 'Lipstick', 'Medical Mask'] }
    ]
  },
  {
    id: 'collection-2',
    name: 'Dreamscape Realms',
    description: 'Immersive 3D environments and virtual real estate for the metaverse',
    creator: '0x99d24A6b4CcB1B6fAA2625fE562bDD9a23260360',
    contractAddress: '0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260360',
    totalSupply: 5000,
    floorPrice: '2.5',
    volumeTraded: '8750',
    createdAt: '2024-02-20T00:00:00Z',
    bannerImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco',
    profileImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco',
    website: 'https://dreamscaperealms.io',
    twitter: 'https://twitter.com/dreamscaperealms',
    discord: 'https://discord.gg/dreamscaperealms',
    verified: true,
    category: 'Virtual Land',
    chain: 'Somnia',
    royalties: 10.0,
    traits: [
      { name: 'Environment', values: ['Forest', 'Desert', 'Ocean', 'Mountain'] },
      { name: 'Size', values: ['Small', 'Medium', 'Large', 'Estate'] },
      { name: 'Resources', values: ['Common', 'Rare', 'Epic', 'Legendary'] }
    ]
  },
  {
    id: 'collection-3',
    name: 'Somnia Skylines',
    description: 'Exclusive digital art pieces depicting futuristic cityscapes on the Somnia network',
    creator: '0x8a1d4d8b6c3e9f2a5b7c4d6e8f1a3b5c7d9e0f2',
    contractAddress: '0x7c8e2d3f4a5b6c9d1e2f3a4b5c6d7e8f9a0b1c2',
    totalSupply: 2500,
    floorPrice: '1.25',
    volumeTraded: '8750',
    createdAt: '2024-02-10T00:00:00Z',
    bannerImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/skylines-banner',
    profileImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/skylines-profile',
    website: 'https://somniaskylines.io',
    twitter: 'https://twitter.com/somniaskylines',
    discord: 'https://discord.gg/somniaskylines',
    verified: true,
    category: 'Digital Art',
    chain: 'Somnia',
    royalties: 8.5,
    traits: [
      { name: 'Time of Day', values: ['Dawn', 'Day', 'Dusk', 'Night'] },
      { name: 'City Type', values: ['Cyberpunk', 'Utopian', 'Futuristic', 'Floating'] },
      { name: 'Rarity', values: ['Common', 'Uncommon', 'Rare', 'Legendary'] }
    ]
  },
  {
    id: 'collection-4',
    name: 'Metaverse Avatars',
    description: 'Unique 3D avatars for use across multiple metaverse platforms',
    creator: '0x9b2e4d6f8a1c3e5f7b9d2c4e6f8a1b3d5f7e9c1',
    contractAddress: '0x6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5',
    totalSupply: 10000,
    floorPrice: '0.75',
    volumeTraded: '15250',
    createdAt: '2024-03-05T00:00:00Z',
    bannerImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/avatars-banner',
    profileImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/avatars-profile',
    website: 'https://metaverseavatars.io',
    twitter: 'https://twitter.com/metaavatars',
    discord: 'https://discord.gg/metaavatars',
    verified: true,
    category: 'Avatar',
    chain: 'Somnia',
    royalties: 7.0,
    traits: [
      { name: 'Species', values: ['Human', 'Alien', 'Robot', 'Animal', 'Mythical'] },
      { name: 'Outfit', values: ['Casual', 'Formal', 'Armor', 'Futuristic', 'Fantasy'] },
      { name: 'Accessory', values: ['Glasses', 'Hat', 'Weapon', 'Tool', 'Pet'] },
      { name: 'Rarity', values: ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary'] }
    ]
  },
  {
    id: 'collection-5',
    name: 'GameFi Champions',
    description: 'Playable characters for blockchain-based games with unique abilities and attributes',
    creator: '0x7c3e5f9a1b4d6e8f2a5c7d9e1b3f5a7c9d2e4f6',
    contractAddress: '0x5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4',
    totalSupply: 5000,
    floorPrice: '3.5',
    volumeTraded: '22500',
    createdAt: '2024-01-20T00:00:00Z',
    bannerImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/champions-banner',
    profileImage: 'https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/champions-profile',
    website: 'https://gamefichampions.io',
    twitter: 'https://twitter.com/gamefichampions',
    discord: 'https://discord.gg/gamefichampions',
    verified: true,
    category: 'Gaming',
    chain: 'Somnia',
    royalties: 10.0,
    traits: [
      { name: 'Class', values: ['Warrior', 'Mage', 'Ranger', 'Healer', 'Tank'] },
      { name: 'Element', values: ['Fire', 'Water', 'Earth', 'Air', 'Light', 'Dark'] },
      { name: 'Rarity', values: ['Common', 'Uncommon', 'Rare', 'Epic', 'Legendary', 'Mythic'] },
      { name: 'Level', values: ['1', '5', '10', '20', '50', '100'] }
    ]
  }
];
