// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

/**
 * @title AIAgentNFT
 * @dev ERC-7857 inspired contract that allows AI agents to be minted as NFTs
 * 
 * This enables:
 * - Ownership of AI agents as verifiable on-chain assets
 * - Trading of successful AI agents
 * - Revenue sharing from agent performance
 * - Provenance and verification of agent capabilities
 * 
 * Based on ERC-7857: Standard for Representing AI Agents as NFTs
 * Adapted for Somnia blockchain's NFTFlow rental marketplace
 */
contract AIAgentNFT is ERC721URIStorage, Ownable {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIds;

    struct AgentMetadata {
        string agentType; // "pricing", "recommendation", "risk_assessment"
        string model; // e.g., "gpt-4o-mini", "custom-v1"
        string capabilities; // JSON string of agent abilities
        uint256 successRate; // Basis points (10000 = 100%)
        uint256 totalActions;
        uint256 totalRevenue; // Revenue generated by this agent
        address originalOwner;
        uint256 createdAt;
        bool isActive;
    }

    struct AgentPerformance {
        uint256 totalRentalsOptimized;
        uint256 totalRevenueGenerated;
        uint256 avgConfidenceScore;
        uint256 lastActiveTimestamp;
    }

    // Token ID => Agent Metadata
    mapping(uint256 => AgentMetadata) public agents;
    
    // Token ID => Agent Performance
    mapping(uint256 => AgentPerformance) public performance;
    
    // Owner => Token IDs owned
    mapping(address => uint256[]) public ownerTokens;
    
    // Agent type => Best performing token IDs
    mapping(string => uint256[]) public topAgentsByType;
    
    // Revenue sharing (basis points, e.g., 1000 = 10%)
    uint256 public platformFee = 500; // 5% goes to platform
    uint256 public constant BASIS_POINTS = 10000;

    // Events
    event AgentMinted(
        uint256 indexed tokenId,
        address indexed owner,
        string agentType,
        string model
    );
    
    event AgentPerformanceUpdated(
        uint256 indexed tokenId,
        uint256 successRate,
        uint256 totalActions,
        uint256 totalRevenue
    );
    
    event RevenueDistributed(
        uint256 indexed tokenId,
        address indexed owner,
        uint256 amount
    );

    constructor() ERC721("AI Agent NFT", "AGENT") Ownable(msg.sender) {}

    /**
     * @dev Mint a new AI agent as an NFT
     * @param agentType Type of agent (pricing, recommendation, etc.)
     * @param model Model identifier
     * @param capabilities JSON string of agent capabilities
     * @param tokenURI Metadata URI
     */
    function mintAgent(
        string memory agentType,
        string memory model,
        string memory capabilities,
        string memory tokenURI
    ) external returns (uint256) {
        _tokenIds.increment();
        uint256 newTokenId = _tokenIds.current();

        agents[newTokenId] = AgentMetadata({
            agentType: agentType,
            model: model,
            capabilities: capabilities,
            successRate: 0,
            totalActions: 0,
            totalRevenue: 0,
            originalOwner: msg.sender,
            createdAt: block.timestamp,
            isActive: true
        });

        performance[newTokenId] = AgentPerformance({
            totalRentalsOptimized: 0,
            totalRevenueGenerated: 0,
            avgConfidenceScore: 0,
            lastActiveTimestamp: block.timestamp
        });

        _mint(msg.sender, newTokenId);
        _setTokenURI(newTokenId, tokenURI);
        
        ownerTokens[msg.sender].push(newTokenId);

        emit AgentMinted(newTokenId, msg.sender, agentType, model);
        return newTokenId;
    }

    /**
     * @dev Update agent performance metrics
     * Only callable by AIAgentManager contract
     */
    function updatePerformance(
        uint256 tokenId,
        bool success,
        uint256 revenueGenerated,
        uint256 confidenceScore
    ) external {
        // In production, add access control check
        require(_exists(tokenId), "Agent does not exist");
        require(agents[tokenId].isActive, "Agent is inactive");

        AgentMetadata storage agent = agents[tokenId];
        AgentPerformance storage perf = performance[tokenId];

        agent.totalActions++;
        agent.totalRevenue += revenueGenerated;
        
        perf.totalRevenueGenerated += revenueGenerated;
        perf.lastActiveTimestamp = block.timestamp;

        // Update success rate
        if (agent.totalActions > 0) {
            uint256 currentSuccess = agent.successRate;
            uint256 totalSuccess = (currentSuccess * (agent.totalActions - 1)) + (success ? 10000 : 0);
            agent.successRate = totalSuccess / agent.totalActions;
            
            // Update average confidence
            uint256 totalConfidence = (perf.avgConfidenceScore * (agent.totalActions - 1)) + confidenceScore;
            perf.avgConfidenceScore = totalConfidence / agent.totalActions;
        }

        // Update total rentals if successful
        if (success) {
            perf.totalRentalsOptimized++;
        }

        emit AgentPerformanceUpdated(
            tokenId,
            agent.successRate,
            agent.totalActions,
            agent.totalRevenue
        );
    }

    /**
     * @dev Distribute revenue to agent owner
     */
    function distributeRevenue(uint256 tokenId, uint256 amount) external {
        require(_exists(tokenId), "Agent does not exist");
        require(ownerOf(tokenId) != address(0), "Agent owner is zero address");

        address agentOwner = ownerOf(tokenId);
        uint256 ownerShare = (amount * (BASIS_POINTS - platformFee)) / BASIS_POINTS;
        uint256 platformShare = amount - ownerShare;

        // In production, actually transfer tokens
        // payable(agentOwner).transfer(ownerShare);
        // payable(owner()).transfer(platformShare);

        emit RevenueDistributed(tokenId, agentOwner, ownerShare);

        agents[tokenId].totalRevenue += amount;
    }

    /**
     * @dev Get agent information
     */
    function getAgentInfo(uint256 tokenId)
        external
        view
        returns (
            AgentMetadata memory,
            AgentPerformance memory,
            address currentOwner
        )
    {
        require(_exists(tokenId), "Agent does not exist");
        return (agents[tokenId], performance[tokenId], ownerOf(tokenId));
    }

    /**
     * @dev Get tokens owned by an address
     */
    function getOwnedTokens(address owner) external view returns (uint256[] memory) {
        return ownerTokens[owner];
    }

    /**
     * @dev Get top performing agents by type
     */
    function getTopAgentsByType(string memory agentType, uint256 limit)
        external
        view
        returns (uint256[] memory)
    {
        return topAgentsByType[agentType];
    }

    /**
     * @dev Toggle agent active status
     */
    function setAgentStatus(uint256 tokenId, bool isActive) external {
        require(_ownerOf(tokenId) == msg.sender || msg.sender == owner(), "Unauthorized");
        require(_exists(tokenId), "Agent does not exist");
        agents[tokenId].isActive = isActive;
    }

    /**
     * @dev Transfer agent ownership
     */
    function _update(address to, uint256 tokenId, address auth) 
        internal 
        virtual 
        override 
        returns (address) 
    {
        address from = _ownerOf(tokenId);
        
        // Remove from old owner's list
        if (from != address(0)) {
            uint256[] storage fromTokens = ownerTokens[from];
            for (uint256 i = 0; i < fromTokens.length; i++) {
                if (fromTokens[i] == tokenId) {
                    fromTokens[i] = fromTokens[fromTokens.length - 1];
                    fromTokens.pop();
                    break;
                }
            }
        }
        
        // Add to new owner's list
        if (to != address(0)) {
            ownerTokens[to].push(tokenId);
        }
        
        return super._update(to, tokenId, auth);
    }

    /**
     * @dev Update platform fee (only owner)
     */
    function setPlatformFee(uint256 newFee) external onlyOwner {
        require(newFee <= 2000, "Fee cannot exceed 20%");
        platformFee = newFee;
    }

    /**
     * @dev Get agent value based on performance
     */
    function calculateAgentValue(uint256 tokenId) external view returns (uint256) {
        require(_exists(tokenId), "Agent does not exist");
        
        AgentMetadata memory agent = agents[tokenId];
        AgentPerformance memory perf = performance[tokenId];
        
        // Value formula based on multiple factors
        uint256 ageMultiplier = (block.timestamp - agent.createdAt) / 86400; // Days active
        uint256 successMultiplier = agent.successRate / 100; // Convert to percentage
        uint256 revenueMultiplier = perf.totalRevenueGenerated / 1e18; // Convert to STT
        uint256 activityMultiplier = perf.totalRentalsOptimized * 10;
        
        // Base value + performance bonuses
        uint256 baseValue = 1e18; // 1 STT base
        uint256 value = baseValue + 
                       (successMultiplier * 1e16) + 
                       (revenueMultiplier / 10) + 
                       (activityMultiplier * 1e15) +
                       (ageMultiplier * 1e15);
        
        return value;
    }

    /**
     * @dev Get current token count
     */
    function totalSupply() external view returns (uint256) {
        return _tokenIds.current();
    }
}

