// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbpmhxewduhmyyloujvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBicG1oeGV3ZHVobXl5bG91anZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjY2MTksImV4cCI6MjA3MzcwMjYxOX0.BYdJ7RYLqNF3cXa2BiCuUzr5B1YsID6pvR-sIPuODeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});